# Generated by Django 4.2.7 on 2023-11-26 14:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "verbose_name": "product categorization",
                "verbose_name_plural": "product categorization",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=80)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                100, message="minimum: 100"
                            )
                        ]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("a", "정상"), ("s", "품절"), ("o", "단종"), ("i", "비활성화")],
                        default="i",
                        max_length=1,
                    ),
                ),
                ("photo", models.ImageField(upload_to="mall/product/photo/%Y/%m/%d/")),
                (
                    "category",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mall.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "product",
            },
        ),
    ]
